### ISSUE TITLE
get_card_name index out of range (using previous card_index from config file)

### ISSUE THREAD

**Issue by jeffeb3** [gen2brain/volti#51]
I plugged in a USB sound card, set the mixer on volti to work with it (card_index 2). 

Then I unplugged it, rebooted, and volti wouldn't start. This is the traceback:

[alsactrl.py:get_card_name:165] list index out of range
[alsactrl.py:__init__:41] can't open Master control for card None, trying to select first available mixer channel

[alsactrl.py:get_card_name:165] list index out of range
[alsactrl.py:__init__:49] can't open first available control for card None
error: list index out of range
[alsactrl.py:get_card_name:165] list index out of range
Traceback (most recent call last):
  File "/usr/bin/volti", line 53, in <module>
    volti = main.VolumeTray()
  File "/usr/lib/volti/volti/main.py", line 124, in __init__
    self.watchid = gobject.io_add_watch(fd, eventmask, self.update)
TypeError: an integer is required

The problem is that the ~/.config/volti/config has a card_index = 2 in it, and there are now only 2 cards. So I changed that back to 0, and it started working. 

It looks like you're trying another mixer, but if the card doesn't exist, you don't try the first card.

**Comment by jeffeb3** [comment]
I should mention, 0.2.3 on lubuntu 14.04
