### ISSUE TITLE
error cannot run

### ISSUE THREAD

**Issue by Ygarr** [gen2brain/volti#63]
Xfce, linux mint sonya

[alsactrl.py:__init__:41] can't open Master control for card HDMI, trying to select first available mixer channel

[alsactrl.py:__init__:49] can't open first available control for card HDMI
error: list index out of range
Traceback (most recent call last):
  File "/usr/bin/volti", line 52, in <module>
    volti = main.VolumeTray()
  File "/usr/lib/volti/volti/main.py", line 124, in __init__
    self.watchid = gobject.io_add_watch(fd, eventmask, self.update)
TypeError: an integer is required

**Comment by LordOfTheRats** [comment]
I have the same issue. I get 
`[alsactrl.py:__init__:41] can't open Master control for card Generic, trying to select first available mixer channel`
when I start volti. Using alsamixer I see, that the soundcard is called `HD-Audio Generic`. I also saw this behavior on another system with a card called `HD-Audio HDMI`. I thing OPs soundcard will also be called `HD-Audio HDMI`.

So it seems volti doesn't like spaces in the name of the soundcard.
