### ISSUE TITLE
Volti does not open internal mixer.

### ISSUE THREAD

**Issue by BlushBerry** [gen2brain/volti#67]
```
Traceback (most recent call last):
  File "/usr/bin/volti-mixer", line 46, in <module>
    mix = mixer.Mixer()
  File "/usr/lib/python2.7/site-packages/volti/mixer.py", line 77, in __init__
    self.init_controls()
  File "/usr/lib/python2.7/site-packages/volti/mixer.py", line 178, in init_controls
    volume.set_level(self.get_volume(n, card_index))
  File "/usr/lib/python2.7/site-packages/volti/mixer.py", line 237, in get_volume
    return (vol[0], vol[1])
IndexError: list index out of range
```

Linux Technetium 4.18.9-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 19 21:19:17 UTC 2018 x86_64 GNU/Linux

Python3 Ver: Python 3.7.0
Python2 Ver: Python 2.7.15

**Comment by BartMassey** [comment]
Same for me. Debian 5.7.6-1 Python2.7. Worked around in PR #69.
